services:
  web:
    build: .
    ports:
      - "8282:8282"
    environment:
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_USER=${CASSANDRA_USER}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS}
      - RATE_LIMIT_WINDOW_SECONDS=${RATE_LIMIT_WINDOW_SECONDS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_DB=${REDIS_DB}
      - REDIS_SALT_KEY=${REDIS_SALT_KEY}
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE}
      - REDIS_MIN_IDLE_CONNS=${REDIS_MIN_IDLE_CONNS}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_DIAL_TIMEOUT=${REDIS_DIAL_TIMEOUT}
      - URL_API_REDIRECT=${URL_API_REDIRECT}
      - URL_AUTH=${URL_AUTH}
      - SERVER_PORT=${SERVER_PORT}
      - ENV=${ENV}
    